title: Michelle Santos
description: Software engineer based in Zürich 🇨🇭
#logo: /assets/img/logo.png
show_downloads: false
theme: jekyll-theme-minimal
email: msantosrieper@gmail.com
linkedin: www.linkedin.com/in/msantosrieper/